name: Build and Deploy to Production

on: [push]

jobs:
  install:
    name: Install
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3

      - name: Run image
          uses: abatilo/actions-poetry@v2
          with:
            poetry-version: '1.1.15'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Poetry Install
        run: poetry install

  test:
    name: Test
    needs: install
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.1.15'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Display structure of downloaded files
        run: ls -R

      - name: Run Tests
        run: poetry run pytest

