name: Build and Deploy to Production

on: [push]

jobs:
  test:
    name: Install
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.1.15'

      - name: Poetry Install
        run: poetry install

  Test:
    name: Test
    needs: test
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.1.15'

      - name: Display structure of downloaded files
        run: ls -R

      - name: Run Tests
        run: poetry run pytest

